<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../JobApplicationTrackerAPI.Domain/JobApplicationTrackerAPI.Domain.csproj" />
    <ProjectReference Include="../JobApplicationTrackerAPI.Application/JobApplicationTrackerAPI.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

</Project>
